### PR TITLE
feat: Added Hue XY Conversions

### PR DESCRIPTION
**Pull request by Tynopia**
Hey there! 😃 

First of all, I want to express my appreciation for this amazing repository, it has saved me hours of work!

I am currently working on a Philips Hue Controller that can send the XY color values derived from the HEX values provided by your UI. To achieve this, I referred to the [official Philips documentation](https://developers.meethue.com/develop/application-design-guidance/color-conversion-formulas-rgb-to-xy-and-back/) and implemented the following XY conversion functions:

- `hexToXY`
- `xyToHex`
- `rgbToXY`
- `xyToRgb`

I hope you find these additions useful!

### CODE REVIEW

**Comment by jaywcjlove** [comment]
@Tynopia  Thank you for your PR! I took some time to learn about XY color values after reviewing your submission, and I think it's a great addition. I’ll go ahead and merge it!

**Comment by jaywcjlove** [comment]
@Tynopia The test cases did not pass.

https://github.com/uiwjs/react-color/actions/runs/10981083176/job/30487717429?pr=155#step:8:23

**Comment by Tynopia** [comment]
Yeah, give me 10 min 👍

**Comment by Tynopia** [comment]
Oops, I'll never say 10 minutes again if it takes 3 hours 😆 . I now have a fix and everything should work now
@jaywcjlove

**Comment by Tynopia** [comment]
Fixed

**Comment by jaywcjlove** [comment]
@Tynopia thx!

**Pull request merged**
